default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  encoding: utf-8

development:
  <<: *default
  database: future_dashboard_development

test:
  <<: *default
  database: future_dashboard_test

production:
  <<: *default
  database: future_dashboard_production
